### ISSUE TITLE
Schedule tabs in landscape wrap labels on two lines

### ISSUE THREAD

**Issue by quiro91** [squanchy-dev/squanchy-android#162]
![screenshot_20170322-145904](https://cloud.githubusercontent.com/assets/1331440/24240441/e9b249de-0fb1-11e7-8e1b-0af1f29874d7.png)

Don't know if we can do anything about this

**Comment by rock3r** [comment]
I'll change this as it's not the real problem :P On a device set in Italian all dates/times are formatted in Italian. That's ok.
