### ISSUE TITLE
Homescreen empty states

### ISSUE THREAD

**Issue by rock3r** [squanchy-dev/squanchy-android#166]
If a page content is empty, it will simply be an empty page. It should have some sort of empty state.

TODO:
 * [x] #336 Schedule
 * [x] Favorites (done in #188)
 * [x] #337 Tweets

**Comment by ScribblyPixels** [comment]
Added the Zeplin preview as well as a design asset in Dropbox
https://zpl.io/awq3Ae7
https://www.dropbox.com/s/mn6znrbeczk32ax/img_emptystate.svg?dl=0

**Comment by rock3r** [comment]
Nice one! Do we have one for the tweets screen too?

**Comment by ScribblyPixels** [comment]
@rock3r No. I will sort that :D

**Comment by rock3r** [comment]
Done, but we're still missing a nicer icon for Twitter from @ScribblyPixels

**Comment by rock3r** [comment]
Closing for now, as swapping the drawable will be an easy task and the core is done here
