### ISSUE TITLE
Opening develop brunch in Android Studio 2.3

### ISSUE THREAD

**Issue by atetc** [squanchy-dev/squanchy-android#178]
Hi!
I have some problems with APPLICATION_ID when trying to open project.

```
Error:A problem occurred while evaluating entry:
- File application.properties does not exist.
- No environment variable defined for key 'APPLICATION_ID'
```

**Comment by rock3r** [comment]
Hello! Please refer to the [setup instructions in the readme](https://github.com/rock3r/squanchy/blob/develop/README.md#setting-up-the-app), they should contain all the necessary details. Let us know if there's anything missing by opening a further issue or, even better, a pull request to improve the docs.
