### ISSUE TITLE
Bottom navigation bar color is incorrect when coming back from stacked activity

### ISSUE THREAD

**Issue by catt-stefano** [squanchy-dev/squanchy-android#180]
![screenshot_20170328-114158](https://cloud.githubusercontent.com/assets/11888433/24399346/bb4f6898-13ac-11e7-9494-b40e72a96171.png)

To reproduce:

- Open schedule

- Open venue info

- Tap map to open Google maps

- Press back, and the bottom navigation is of the wrong color

Witnessed on a Samsung Galaxy A5 (2016). Don't mind the map image, is just for testing.

**Comment by rock3r** [comment]
I cannot reproduce it on `develop`, can you check there too?

**Comment by tiwiz** [comment]
Yes, just did, I could replicate it on `develop` as well. Investigating it now.
