### ISSUE TITLE
Remove the 2 lines fix to set the theme.

### ISSUE THREAD

**Issue by tiwiz** [squanchy-dev/squanchy-android#184]
Properly sort out "hotfix" related to issue #180  in the `HomeActivity` `onResume()`

**Comment by fourlastor** [comment]
https://github.com/squanchy-dev/squanchy-android/blob/develop/app/src/main/java/net/squanchy/home/HomeActivity.kt#L107-L109

This seems like it's been fixed, or the TODO removed, still valid?

**Comment by rock3r** [comment]
Should be fixed. Closing!
