### ISSUE TITLE
NearITManager adds listener to app lifecycle in constructor

### ISSUE THREAD

**Issue by fourlastor** [squanchy-dev/squanchy-android#189]
As discussed in #171, we should have an explicit method for this so that we won't be surprised on why we're instantiating the `ProximityService` in the application `onCreate` without using it.

An option is to have `ProximityService.registerToApplicationLifecycle` and that will then call `NearITManager.registerToApplicationLifecycle`.

**Comment by rock3r** [comment]
We don't have NearIt anymore as of #309 so this is obsolete
