### ISSUE TITLE
Import JSON from call for paper server

### ISSUE THREAD

**Issue by rock3r** [squanchy-dev/squanchy-android#24]
We need to be able to import a raw data export from the Droidcon Turin Call for Papers backend into the Connfa backend.

**Comment by tiwiz** [comment]
**UPDATE:** we are expecting two calls (`get_Talk` and `get_Speaker`) that should return all the data we need.

**Comment by tiwiz** [comment]
[Here](https://gitlab.com/tiwiz.dev/droidcon-parser) there is the very basic converter
