### ISSUE TITLE
Make debug keystore part of the project conf

### ISSUE THREAD

**Issue by fourlastor** [squanchy-dev/squanchy-android#275]
This should be in `team-props` probably, and it should be git ignored, and then referenced in `build.gradle` to be used with the debug build. This way we solve the issue with having devs not being able to sign in users via google credentials.

- [x] Add steps to setup to README file.
- [x] Add `debug.keystore` to `.gitignore`.

Part of #344

**Comment by rock3r** [comment]
Done.
