### ISSUE TITLE
Improve push notifications appearance

### ISSUE THREAD

**Issue by rock3r** [squanchy-dev/squanchy-android#339]
We're currently using the default icon and copy, we should customise that. MVP is just text, we could want to have bigImage/bigText support too in the future, but for now it's ok to just have a basic setup.

Part of #86

**Comment by ScribblyPixels** [comment]
@rock3r Can you by any chance do me a screenshot of an Android O (if possible) notification? :). I don't have the OS on any devices.  Just interested to see the precise pixel output
