### ISSUE TITLE
Switch data layer implementation to Firestore

### ISSUE THREAD

**Issue by rock3r** [squanchy-dev/squanchy-android#367]
We want to migrate to Firestore to simplify the code on the client side thanks to indexes and queries support in Firestore, that we have to emulate with RTDB.

 * [x] Schedule
 * [x] Tweets
 * [x] Venue info
 * [x] Favourites
 * [x] Event details
 * [x] Speaker details
 * [x] Conference info
 * [x] Remove any leftover RTDB code

**Comment by quiro91** [comment]
@rock3r what does bits and bobs refer to? Is there anything else besides search and favourites at this point?

**Comment by rock3r** [comment]
Bits and bobs is making sure we haven't forgotten anything, and removing the Firebase RTDB entirely :)

**Comment by quiro91** [comment]
I removed the search from the checklist, it's worth to have a separate ticket for it. This ticket should be considered as done
