### ISSUE TITLE
Http2Stream.java line 593

### ISSUE THREAD

**Issue by rock3r** [squanchy-dev/squanchy-android#378]
#### in okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/squanchy/android/apps/net.squanchy.london17/issues/59ef7cf761b02d480d21ab3d?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/squanchy/android/apps/net.squanchy.london17/issues/59ef7cf761b02d480d21ab3d?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by quiro91** [comment]
As we are removing the Twitter client this will be fixed in #286
