### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [squanchy-dev/squanchy-android#528]
Hi good day! I would like to ask for your permission to propose a new designs of logo in your application/project. This issue is not saying that your current logo is unsatisfactory, I would just like to propose new designs. Hoping for your positive response Thank You!

**Comment by rock3r** [comment]
Hey there! First of all, thanks for your interest :)

We are actually [looking forward](https://github.com/squanchy-dev/meta/issues/1) to define a better brand identity (including a new logo), but unfortunately so far our designers haven't had any bandwidth. If you'd like to take a stab at it, please feel free to — this is a FOSS project and everyone is welcome to contribute!

In that case, would you care to open a PR on the [`meta`](https://github.com/squanchy-dev/meta) repository once you have something, so we can start discussing it?

**Comment by rock3r** [comment]
Full disclosure, @ScribblyPixels did start playing around with typography and palettes. We have something in drafts on our projects but we don't currently have a publicly shared file for that.

**Comment by rock3r** [comment]
I'll close this for now.
