### ISSUE TITLE
Make instant app

### ISSUE THREAD

**Issue by rock3r** [squanchy-dev/squanchy-android#536]
If we want to eventually support Instant Apps (which we should) we need to start modularising things a lot. It will also give us significative advantages in build times.

**Comment by rock3r** [comment]
CC @sockeqwe

Let's plan things here. I'm up for a catch-up call this evening. @quiro91 ?

**Comment by quiro91** [comment]
I'm up for it too

**Comment by sockeqwe** [comment]
What do you think about the following folder strategy (assuming Services have not been renamed to Repositories yet):
 - **app** 
- **schedule** (just a folder)
    - **schedule-service** (java lib gradle module that basically contains just  the `ScheduleService` interface; depends on `schedule-domain`)
    - **schedule-service-firestore** ( android lib gradle module; depends on `schedule-service`)
    - **schedule-service-local-db** ( android lib gradle module; depends on `schedule-service`; uses local sqlite database)
    - **schedule-domain** (java lib gradle module containing classes like `Day`, `Event` etc.)
    - **schedule-presentation** (android lib containing presentation / UI like `SchedulePageView`; depending on  schedule-service)

The same pattern could be applied to other "features / services" like search, speaker, favorites and so on.

**app** module  then does all the dependency injection stuff and each conference can decide which **scheduler-service** implementation to use (schedule-service-firestore or schedule-service-local-db)

What do you think?

**Comment by rock3r** [comment]
Seems like a reasonable division. We can iterate on things again later on if we see it doesn't work well for schedule!

**Comment by sockeqwe** [comment]
Cool, I'm working on it. Will come back with a pull request soon.

**Comment by rock3r** [comment]
That's great, thanks Hannes :)

**Comment by rock3r** [comment]
We don't really need to modularise urgently for instant apps, since the limit is 10 MB and we're well below that, but we should focus on providing instant app capabilities!

See https://medium.com/androiddevelopers/the-android-dev-summit-2018-app-instant-app-takeaways-open-source-e5b590f78f38
