### ISSUE TITLE
Clicking on Speaker's twitter icon is broken (failing with "User not found")

### ISSUE THREAD

**Issue by cortinico** [squanchy-dev/squanchy-android#551]
App version: `1.1.0-dcit18`
OS version: `8.1.0`

Looks like clicking on the speaker's twitter icon to open the speaker's profile is not working properly.
How to reproduce:

1. Open the app
2. Click on the Search icon
3. Click on one of the speaker avatar
4. Click on the twitter icon in the top right

The app will fail to link and will show a "User not found" toast.
![ezgif-4-4f4643cf36](https://user-images.githubusercontent.com/3001957/38683823-a0e07b58-3e6e-11e8-8b6c-91213a96b720.gif)

**Comment by rock3r** [comment]
Thanks for reporting this! Seems like it's partly a backend issue (Syx never validated the data so there's all sorts of random stuff in there), and partly an app issue. We'll get it fixed ASAP.

**Comment by rock3r** [comment]
Turns out we could fix it entirely on the backend: https://github.com/squanchy-dev/squanchy-firebase/pull/57 you should not have any issues anymore.
