### ISSUE TITLE
Screen: venue info

### ISSUE THREAD

**Issue by rock3r** [squanchy-dev/squanchy-android#57]
Contains: venue name and address (plus map?), directions link.

Non-MVP: venue info (transport close by, etc), room info (capacity), floor plans

**Comment by danybony** [comment]
MVP done in https://github.com/rock3r/squanchy/pull/158 and https://github.com/rock3r/squanchy/pull/160

**Comment by rock3r** [comment]
New version from specs: https://zpl.io/ZeWkQe
