### ISSUE TITLE
Is it ok to add a Sponsors section?

### ISSUE THREAD

**Issue by sockeqwe** [squanchy-dev/squanchy-android#576]
For Droidcon Berlin 2018 we would like to use squanchy as a base.
However, Droidcon Berlin asked me if it would be ok to add a sponsors section somewhere in the app.

How do you feel about it? Would it be ok from your point of view to use your app and add a sponsors section?

**Comment by rock3r** [comment]
I would personally be ok with it if it weren't in the top level navigation — i.e., not have a dedicated section in the bottom nav bar in the homescreen. In fact I'd like to be able to have pluggable modules for such non-core features, that one can enable or remove at build time. I think it'll need some serious thinking upfront to get that right, though, and we still need to properly modularise everything first anyway.

I would for now proceed like this:
 1. Let's discuss where the sponsors section shows up
     * I would think it'd be fair to have it in the settings screen, or at the bottom of the venue page, or in the onboarding
 2. Once we pick where it shows up, we can decide how to put it in — I'd think it could be implemented mostly in a separate module, with just a feature flag on the app side defining whether is shows up or not

Thoughts?

**Comment by sockeqwe** [comment]
Fair enough, not putting sponsors in top level navigation should work.  Regarding modularization, I think we should move this discussion in its own ticket like #536
