### ISSUE TITLE
Project Logo

### ISSUE THREAD

**Issue by debpedrano** [squanchy-dev/squanchy-android#581]
Greetings,

Your project is getting bigger, I think its time to have a logo for it. If it is okay to you, I will submit my design.

**Comment by debpedrano** [comment]
Hello, can I update the issue?

**Comment by rock3r** [comment]
Sure thing; we reserve to evaluate your contribution like everybody else's before approving it though. Hope you understand.

**Comment by debpedrano** [comment]
Okay, great! I am still a beginner on this profession but ill be giving my best to have a good quality output, thanks!

**Comment by debpedrano** [comment]
You can see SQ on the logo, I made three different kinds but it looks similar. 
SQ for the start of squanchy

![image](https://user-images.githubusercontent.com/40510200/47953002-3fa8cd00-dfb2-11e8-85d9-4d169762c8fb.png)

**Comment by rock3r** [comment]
Hey there, sorry I completely forgot to reply. Right now we're having @ScribblyPixels rethink our whole branding and UI so we're putting this on hold. We are aiming at a cohesive branding and this may or may not align with what we're going to come up with — we don't know yet, although if I were to be completely honest it seems a bit unlikely, as the chances of a fortuitous alignment are pretty slim.
