### ISSUE TITLE
Description has too small area if title of talk is too long

### ISSUE THREAD

**Issue by emartynov** [squanchy-dev/squanchy-android#593]
Subject https://photos.app.goo.gl/gXL8pYfM1mDJ1Vfd8

**Comment by rock3r** [comment]
Yeah, known issue :) The designs call for the appbar to collapse but it's very tricky and we had to deprioritise it as it was less important than making the app not crash 😅 But it's tracked already #161 so I'm closing this. Thanks for reporting! Hope you're enjoying the app.
