### ISSUE TITLE
App bootstrap package for offline first launch

### ISSUE THREAD

**Issue by rock3r** [squanchy-dev/squanchy-android#602]
The app right now requires a working connection on first start since Firestore needs to download its data. Ideally we should be able to make sessions available at first launch while offline too.

A possible strategy is to move session data out of Firestore and into a statically generated (series of) JSON file(s) that can be hosted somewhere and updated manually when session data changes. This requires a function to generate said JSON file(s) and send a FCM push to all apps telling them to get the fresh data. We still store the favourites in Firestore (that feature still requires connectivity to auth).

h/t to @JoseAlcerreca for the great discussion we had on the topic a couple months back :)

**Comment by JoseAlcerreca** [comment]
We ended up downloading the JSON data on app launch (or trying to) in ADS, as it was only 100Kb and we weren't expecting too many changes. We downloaded every time but in the future we should check the modified date in the header, or something similar, before downloading it.

Using FCM for fixing a typo seemed like a waste, so we only used it in emergencies (room changes, etc.)

**Comment by rock3r** [comment]
Thanks @JoseAlcerreca :) Ideally we'd only use FCM for emergency changes, yeah — and then have an if-modified-since HTTP check (assuming Firebase Hosting has etags and all). Schedule data is indeed unlikely to change much, so I like your approach better than what we have today.
