### ISSUE TITLE
Crash when opening AboutActivity

### ISSUE THREAD

**Issue by cmargonis** [squanchy-dev/squanchy-android#631]
Hello and thanks a lot for putting in place this awesome system 😄 
During my efforts of setting up squanchy for Droidcon Greece 2019 I stumbled upon a crash.

### Environment Observed on
- App Version: commit 998a3b9
- OS Version: Any

### Steps to reproduce
- Open `AboutActivity`
- App crash with: `ApplicationComponent` has not been set

### Solution
In `AboutComponent.kt` modify it like so:

```kotlin
fun aboutComponent(activity: AppCompatActivity): AboutComponent =
    DaggerAboutComponent.builder()
        .applicationComponent(activity.applicationComponent) // add this line
        .activity(activity)
        .build()
```
I would be more than happy to provide a Pull Request for this issue 😄

**Comment by quiro91** [comment]
Hey @cmargonis, good catch! Feel free to open a PR! :)

**Comment by cmargonis** [comment]
Closing this since #632 was merged 😄
